# Generated by Django 2.2 on 2019-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=215, null=True)),
                ('lastname', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=215, null=True)),
                ('email', models.EmailField(max_length=215, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('photo', models.ImageField(default='Phots/None/No-img.jpg', upload_to='Photos/')),
                ('modefied_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
