# Generated by Django 2.2 on 2019-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasifiedapp', '0002_auto_20190428_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
